### ISSUE TITLE
Seems to incorrectly detect mimecast-hosted mailservers as not supporting STARTTLS

### ISSUE THREAD

**Issue by davidillsley** [hardenize/hardenize-public#12]
eg [royalalberthall.com](https://www.hardenize.com/report/royalalberthall.com/1512233666#email)

Testing with another service (checktls.com), it appears that it in fact does.

**Comment by ivanr** [comment]
I think Hardenize is not wrong in this case. Some of the servers seem to support STARTTLS, but some don't. You can see the difference in the capabilities by hovering the mouse pointer over the "Operational" column. Some servers don't have STARTTLS as a listed feature.

https://www.hardenize.com/report/royalalberthall.com/1512233666#email

![image](https://user-images.githubusercontent.com/485278/33517917-5b175dc2-d784-11e7-874f-3fa9950a464b.png)


I'd guess that checktls.com checks only one server and that one happens to support STARTTLS.

**Comment by davidillsley** [comment]
*sigh* weirder than even that, it seems to vary even on the same host/ip eg 
eu-smtp-inbound-2.mimecast.com
91.220.42.211 in https://www.hardenize.com/report/wintoncapital.co.uk/1512293332#email doesn't,
but
eu-smtp-inbound-2.mimecast.com
91.220.42.211 in https://www.hardenize.com/report/royalalberthall.com/1512233666#email does.

**Comment by ivanr** [comment]
It could be different servers responding to the same IP address. However, it may also be related to the rate access control; IIRC, some servers can be configured not to offer encryption to servers that are on a blacklist.

**Comment by ivanr** [comment]
The report now shows that STARTTLS is supported by all servers, so closing this case.
