### ISSUE TITLE
Wrong Cipherlist displayed? (Hardenize vs. openssl s_client)

### ISSUE THREAD

**Issue by Darkspirit** [hardenize/hardenize-public#13]
https://www.hardenize.com/report/bugzilla.mozilla.org/1512053405#www_tls
They seem to prefer AES128-GCM-SHA256. (I've reported this to them.)
SSLLabs shows the same result as openssl s_client: https://www.ssllabs.com/ssltest/analyze.html?d=bugzilla.mozilla.org&hideResults=on&latest

openssl s_client -connect bugzilla.mozilla.org:443 -servername bugzilla.mozilla.org
> New, TLSv1.2, Cipher is AES128-GCM-SHA256

openssl s_client -connect bugzilla.mozilla.org:443 -servername bugzilla.mozilla.org -cipher "ECDHE-RSA-AES128-GCM-SHA256:AES128-GCM-SHA256"
> New, TLSv1.2, Cipher is AES128-GCM-SHA256

openssl s_client -connect bugzilla.mozilla.org:443 -servername bugzilla.mozilla.org -cipher "ECDHE-RSA-AES128-GCM-SHA256"
> New, TLSv1.2, Cipher is ECDHE-RSA-AES128-GCM-SHA256

**Comment by ivanr** [comment]
From what I was able to determine, both are technically correct. The suites displayed by Hardenize are the suites selected by bugzilla.mozilla.org when we talk to it, in exactly that order. With OpenSSL, the results are different. Clearly there will be differences in the TLS handshakes that cause the web site to choose a different path, although I don't know what they are.

What's the link to your report to Mozilla? Perhaps that will shine some light on what's going on, making it easy to "fix" in Hardenize.

**Comment by Darkspirit** [comment]
I forgot  to write "PFS" in the bug title at first. https://bugzilla.mozilla.org/show_bug.cgi?id=1410573
> Did you mean to say that it's not preferring a cipher that is forward secret? In that case, I agree with you. We're not using the intermediate profile in the correct order: we should be preferring ECDHE over RSA in the handshake, as the intermediate profile orders them. Not sure if WebOps or the BMO team is responsible for the web front end, but it's probably a bug that should get fixed.

> TLS is terminated at the load balancer.  I'll spin off another bug for checking the cipherlist order.

https://observatory.mozilla.org/analyze.html?host=bugzilla.mozilla.org#tls
> Cipher Preference:Server selects preferred cipher
> AES128-GCM-SHA256 at first

https://www.ssllabs.com/ssltest/analyze.html?d=bugzilla.mozilla.org&hideResults=on&latest
> TLS 1.2 (suites in server-preferred order)
> TLS_RSA_WITH_AES_128_GCM_SHA256 (0x9c)

https://www.hardenize.com/report/bugzilla.mozilla.org/1512053405#www_tls
> Server suite preference [yes]
> TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

**Comment by ivanr** [comment]
This ticket seems to no longer hold true. From a quick look, Hardenize and SSL Labs show the same cipher suite order.

**Comment by Darkspirit** [comment]
Confirmed. Bugzilla moved to AWS.
