### ISSUE TITLE
Checking for _domainkey.domain.tld

### ISSUE THREAD

**Issue by Tributh** [hardenize/hardenize-public#15]
Hi,
the DNS entry for _domainkey.*.* was mentioned in RFC4870 Chapter 3.6
Actually still a lot of mailsystems having this obsolete entry in place.
Some DNS TXT samples:
```
t=n;o=~
t=n; o=~; n=http://pages.ebay.com/securitycenter
t=n;o=~;n=http://www.emarsys.com/en/privacy-policy/
t=n; o=~; n=http://www.payback.de/pb/datenschutz/index.html
t=s; o=-;
```

Could this historic and obsolete setting also be tested and marked on the hardenize site?
Kind regards 
         Torsten

**Comment by ivanr** [comment]
Hi Torsten. I am not sure, what value is there in showing this information? Practically speaking, at this time we have a long queue of things to add to the assessment, so even if we do domain keys, it's not going to be soon.

**Comment by Tributh** [comment]
Hi Ivan,
I didn't estimated this to be soon. You alread provide a lot of details around mailservers and I just suggest to make details a bit more complete. As the past shows, a lot of problems and security issues arise just on not maintaining systems to be up to date. If old stuff remains, it brought often enough compatibility or security issues. I am not seeing an arising issue on that yet, but there will be someone coming and shows us. My imagination is just, that configuration should be maintained to the actual standards and remove old stuff for better practice. Maybe that is reason enough.

**Comment by ivanr** [comment]
Yes, you have a point. There is something I can do quickly: I've added the _domainkey label to our DNS inspection test, so even though we don't have an analysis of the contents, it will show on the DNS configuration page: https://www.hardenize.com/report/emarsys.com/1516181168#domain_dns

I am going to close this issue for now and we'll see if it comes up again in the future, after we're done with other, current, stuff. Thanks!
