### ISSUE TITLE
DMARC check insufficient

### ISSUE THREAD

**Issue by Tributh** [hardenize/hardenize-public#22]
As in:
https://www.hardenize.com/report/check24.de/1519176493
The report says:
Policy is valid
Although syntactically valid, ...
Which is wrong, as I also learned recently

The RFC (https://tools.ietf.org/html/rfc7489#section-6.4) states that the tags 
dmarc-version ("v=") and 
dmarc-request ("p=") 
MUST be on the first and second position of the DMARC record.
From the RFC:
             ; components other than dmarc-version and
             ; dmarc-request may appear in any order

Cheers Torsten

**Comment by ivanr** [comment]
Fixed in v0.534 https://www.hardenize.com/report/check24.de/1519313125#email_dmarc Thanks!
