### ISSUE TITLE
Improve HTTP Public Key Pinning check

### ISSUE THREAD

**Issue by Tributh** [hardenize/hardenize-public#24]
I can't see a hint that the given report-uri is checked for validity.
Could be done with a domain-check and/or HEAD request.
Saw too many already got invalid report-uri's.

Cheers Torsten

**Comment by ivanr** [comment]
No plans to do that for HPKP specifically, because HPKP is dead. Generally, speaking, we're planning to check all endpoints, although to do it properly each standard will have to support a test mode. Here's where I suggested it for Expect-CT https://github.com/httpwg/http-extensions/issues/416

**Comment by Tributh** [comment]
The information that HPKP is dead is actually not spreaded enough. We will see how long it will take to get to know to everybody. Your suggestions for the Expect-CT sounds good.
