### ISSUE TITLE
#domain_dnssec should display the result for the tested (sub)domain

### ISSUE THREAD

**Issue by Darkspirit** [hardenize/hardenize-public#32]
https://www.hardenize.com/report/wiki.mozilla.org/1523305681#domain_dnssec
"[Test mozilla.org @ DNSViz](http://dnsviz.net/d/mozilla.org/dnssec/)" should be "[Test wiki.mozilla.org @ DNSViz]( http://dnsviz.net/d/wiki.mozilla.org/dnssec/)"

**Comment by ivanr** [comment]
Fixed in the repo, will be deployed with a day or two. Thanks!
