### ISSUE TITLE
Please add support for the new CAA "validation-methods" + "account-uri" parameters

### ISSUE THREAD

**Issue by Darkspirit** [hardenize/hardenize-public#33]
https://community.letsencrypt.org/t/acme-caa-validation-methods-support/63125
https://community.letsencrypt.org/t/caa-validation-methods-invalid-format/63804/2
https://tools.ietf.org/html/draft-ietf-acme-caa-04

https://www.hardenize.com/report/terrax.net/1529412669#domain_caa
> **Invalid tag value**
> Tag value: letsencrypt.org; validation-methods=dns-01
> Message: Invalid syntax.
> Tag name: issue

**Comment by ivanr** [comment]
This does not appear to be a bug in Hardenize, as the dash in the parameter name ("validation-methods") violates the CAA RFC. Not sure what the background story is here and will investigate before any changes are made.

**Comment by ivanr** [comment]
Relevant thread: https://www.ietf.org/mail-archive/web/acme/current/msg02785.html

**Comment by Darkspirit** [comment]
It has been fixed. Thank you for giving feedback there! :)
https://tools.ietf.org/rfcdiff?url2=draft-ietf-acme-caa-05.txt
https://github.com/letsencrypt/boulder/pull/3772

https://www.hardenize.com/report/terrax.net/1529621073#domain_caa
