### ISSUE TITLE
Expect-CT test with unclear result

### ISSUE THREAD

**Issue by Tributh** [hardenize/hardenize-public#34]
Hi,
https://www.hardenize.com/report/samel.de/1529238962#www_expect_ct
shows an Expect-CT failure.
It looks like the parsing is not checking it well.

Under:
https://securityheaders.com/?q=samel.de&followRedirects=on
this error is not shown.

What could be wrong now?

Kind regards
  T.Tributh

**Comment by ivanr** [comment]
You need to put the URL in double quotes. Although quotes are not required, not all characters are allowed that way, and colon (for example) is one of them. See here for the formal definition of token: https://tools.ietf.org/html/rfc7230#section-3.2.6

**Comment by Tributh** [comment]
Thanx, that explains the issue.
