### ISSUE TITLE
MTA-STS - certificate check

### ISSUE THREAD

**Issue by wioxjk** [hardenize/hardenize-public#36]
Quick question:
Would it not make sense to include the mailserver certificate also in the check?
Right now, it the certificate served over HTTPS for mta-sts.domain.com is shown, but it would make sense if the certificate was shown also and evaluated too. 
I am pretty sure that self signed certificate wont work with MTA-STS

**Comment by ivanr** [comment]
That's what we do. If you don't have MTA-STS and have a self-signed certificate, that's a warning only. If you deploy MTA-STS, you'll see an error instead.

**Comment by wioxjk** [comment]
That's is not what I meant.
On the MTA-STS result "tab", the only certificate that is shown is just the mta-sts webhost and not the mailserver also.

**Comment by ivanr** [comment]
We already have this information in its main location. I think it would be confusing to show a duplicate of it in another place. So, no for now. This is not to say I am perfectly happy with the current design, but we need to evolve it carefully.
