### ISSUE TITLE
Add possible DKIM existence

### ISSUE THREAD

**Issue by Tributh** [hardenize/hardenize-public#38]
Hi,
SPF,DKIM & DMARC are mostly mentioned together.
Actually there is no DKIM test on your site.

It is clear that a DKIM-key could only be checked if the name of the selector is known.
On the site internet.nl they use the following check (text copied from their site):

Verdict:
Your domain supports DKIM records.
Test explanation:
We check if your domain supports DKIM records. A receiving mail server can use the public key in your DKIM record to validate the signature in an email with a user from your domain as sender and determine its authenticity. Currently we are not able to evaluate the public key in your DKIM record, because we would need to receive an email from your domain to do so. To pass this test we expect your name server to answer NOERROR to our query for _domainkey.example.nl. When _domainkey.example.nl is an ‘empty non- terminal’ some name servers that are not conformant with the standard RFC2308 incorrectly answer NXDOMAIN instead of NOERROR. This makes it impossible for us to detect support for DKIM records.

With a lot of different domain and an amount pointing to the same DNS Server there should be a possibilty to give the following results:

a) _domainkey.example.nl give NOERROR which suggests an existing DKIM-key

b)_domainkey.example.nl gives NXDOMAIN, which means there is no KEY or the DNS-Server answers wrong
   Here the verification over many domains on the same DNS-Server make it more clear if all domains getting an NXDOMAIN answer, or only the tested one. Tham on only one has not configured any DKIM-Key

Maybe such a check can be added to hardenize.

Torsten

**Comment by ivanr** [comment]
Hi Torsten, thanks for that research. Although this is something that could be added, I don't really see value in doing it. I'd prefer to spend time on doing the "real thing", which is having web sites send us email on which we can verify DKIM :)

**Comment by Tributh** [comment]
Hi Ivan, when you will spend time to the "real thing", would you like to add an ARC Header's check too?
https://tools.ietf.org/html/draft-ietf-dmarc-arc-protocol-15

**Comment by ivanr** [comment]
Yes, that too is on the TODO list.
