### ISSUE TITLE
Add check for SMTP TLS Reporting

### ISSUE THREAD

**Issue by Tributh** [hardenize/hardenize-public#40]
Hi,
there could be an extra check for
_smtp._tls.example.org

Details:
the latest draft is available here:
https://tools.ietf.org/html/draft-ietf-uta-smtp-tlsrpt-23
and the IESG has already approved the document as Proposed Standard

Torsten

**Comment by ivanr** [comment]
Made a tiny little bit of progress today; we now show TLSRPT configuration in the DNS configuration: https://www.hardenize.com/report/hardenize.com/1531948112#domain_dns :)

**Comment by ivanr** [comment]
Here you go: https://www.hardenize.com/blog/smtp-tls-reporting-tls-rpt
