### ISSUE TITLE
MTA-STS Results give false negative

### ISSUE THREAD

**Issue by MacLemon** [hardenize/hardenize-public#41]
Summary:
MTA-STS Results give false negative

Steps to Reproduce:
Create multiple TXT records for _mta-sts.example.com with valid or invalid record contents.
Run hardenize against example.com and check the results for MTA-STS.

Expected Results:
Having multiple MTA-STS DNS RRs is prohibited by by RFC 8461.

> The TXT record MUST begin with the sts-version field; the order of
> other fields is not significant.  If multiple TXT records for
> "_mta-sts" are returned by the resolver, records that do not begin
> with "v=STSv1;" are discarded.  **If the number of resulting records is**
> **not one, or if the resulting record is syntactically invalid, senders**
> **MUST assume the recipient domain does not have an available MTA-STS**

Actual Results:
Hardenize does not catch if there are multiple MTA-STS RRs and incorrectly gives a green light while it should evaluate this situation as “MTA-STS not available”.

Regression:
n/a

Version Information:
Hardenize v1.0.923 beta

**Comment by ivanr** [comment]
Thanks for a great bug report :) Any chance you can share your host with multiple MTA-STS indicators? If you can, it will help us fix the bug faster.

**Comment by MacLemon** [comment]
Sorry, that was my own domain due to a mishap with the DNS admin interface. I had to fix it since that's a production domain.

I've set up a testing domain:
```
_mta-sts.lionbook.info descriptive text "v=STSv1\;id=invalidrecord\;"
_mta-sts.lionbook.info descriptive text "v=STSv1\;id=Dvw22sWqLcFr7fEXjskkpwAg8VHhECst\;"
```
The rest is not there, so this can not pass the whole test, but should be enough for the DNS check for a single valid record.

**Comment by ivanr** [comment]
This is now fixed: https://www.hardenize.com/report/lionbook.info/1538481884#email_mta_sts

Thanks for your bug report and for your help!

**Comment by MacLemon** [comment]
Awesome, thanks a bunch!
