### ISSUE TITLE
TLSv1.3 cipher not recognized on mailserver

### ISSUE THREAD

**Issue by Tributh** [hardenize/hardenize-public#46]
Hi,
an TLSv1.3 enabled mail server with ECDSA only certificate is not measured correct.
All TLSv1.3 ciphers are not shown
https://www.hardenize.com/report/spricknet.de/1543305130#email_tls

Cheers Torsten

**Comment by ivanr** [comment]
This problem has now been fixed, for now deployed only in our staging environment: https://staging.hardenize.net/report/spricknet.de/1544526908#email_certs Thanks for your bug report!
