### ISSUE TITLE
#email=green,empty + #email_tls=grey,has results + #email_certs=grey

### ISSUE THREAD

**Issue by Darkspirit** [hardenize/hardenize-public#5]
https://www.hardenize.com/report/bundesbank.de/1507320583#email **green, empty**
https://www.hardenize.com/report/bundesbank.de/1507320583#email_tls **grey, but has results**
https://www.hardenize.com/report/bundesbank.de/1507320583#email_certs **grey**

**Comment by ivanr** [comment]
The reported bug has been fixed. Thanks!

There are two further issues in that report, strictly speaking not bugs, but certainly something we need to work around. I've opened separate tickets for them (#6 and #7).
