### ISSUE TITLE
Add gentoo.org to slow list

### ISSUE THREAD

**Issue by ghost** [hardenize/hardenize-public#59]
Please add gentoo.org to the slow list.

> Server refused service: 421 4.7.0 smtp.gentoo.org Error: too many connections from 2600:1f18:753:1b00:eb42:a50a:13c8:2f67

https://www.hardenize.com/report/gentoo.org/1556001303

**Comment by ivanr** [comment]
Done. https://www.hardenize.com/report/gentoo.org/1556001303#email_tls

BTW, on that report, the CAA error is correct and the SPF one isn't because we currently don't handle SPF macros.
