### ISSUE TITLE
Certificate expiry date not accurate

### ISSUE THREAD

**Issue by teamojo** [hardenize/hardenize-public#62]
When I test quality.org, hardenize tells me the web certificate is expired.
Yet, when I open the site in the browser (either Chrome or FF), the certificate appears to have been renewed. Is this likely to be a bug, caching issue or some other explanation?
![Screenshot_1](https://user-images.githubusercontent.com/51291722/58762640-b78ba580-8549-11e9-9376-3934076f911e.png)
![Screenshot_2](https://user-images.githubusercontent.com/51291722/58762615-6380c100-8549-11e9-8713-11fe52b009f8.png)

**Comment by ivanr** [comment]
The explanation is that it's an expired certificate :) Try https://quality.org.

That page shows two certificates, one valid, one not. The expired certificate is installed on quality.org, the non-expired one on www.quality.org.

**Comment by teamojo** [comment]
Thanks Ivan, missed that.
