### ISSUE TITLE
Hardenize does not validate DANE-EE 3 1 1 configurations correctly

### ISSUE THREAD

**Issue by bartbutler** [hardenize/hardenize-public#64]
I sincerely hope that this is not a case of user error. If it is, my apologies.

I added the follow TLSA record to the protonmail.ch zone earlier today:

`_25._tcp.mailsec                IN	TLSA            3 1 1 76BB66711DA416433CA890A5B2E5A0533C6006478F7D10A4469A947ACC8399E1`

This record matches our certificate public key and every other DANE SMTP validator I tried said the configuration was fine. Hardenize, however, did not validate it. While I think this is a bug on Hardenize's end, I have removed the DNS record for the time being as looking bad on Hardenize is a potential PR issue for us. Can you guys please take a look?

**Comment by bartbutler** [comment]
Could be related to #57 , as we also updated our certificates this morning.

**Comment by bartbutler** [comment]
Looks like our old certificates are cached, which would explain it. I will reopen the issue if that does not solve the problem. Sorry for the noise.

**Comment by ivanr** [comment]
@bartbutler Yes, there is some caching going on, and it's a bug. I'll reach out via email to sort this out for you.
