### ISSUE TITLE
Drop support for Email DANE SMTP

### ISSUE THREAD

**Issue by HLFH** [hardenize/hardenize-public#66]
Hi,

After having been an early adopter of DANE, I do think Email DANE SMTP check support should be dropped.

On 18/04/2019, [URIports blog](https://www.uriports.com/blog/mta-sts-explained/) said:

> DANE [for SMTP] and MTA-STS serve the same purpose

[Shumon Huque](https://blog.apnic.net/2019/07/05/whither-dane/) said on 05/07/2019:
> The one area where DANE has had some deployment success to date is in SMTP Transport Security, where it provides a downgrade-resistant way to perform TLS authentication of an SMTP server

In my opinion, it is a redundant offering, and instead of using both, it would be good to take sides.
DANE for SMTP had a relative success but I'm advocating MTA-STS will dominate in the next years.

After Gmail support of MTA-STS, [ProtonMail stated](https://protonmail.com/blog/security-updates-2019/):

> In recent months, we have added support for MTA-STS, DANE

No side is actually taken by ProtonMail. But I am sure it will be. I no longer see where DANE is going. The Internet Draft _[A DANE Record and DNSSEC Authentication Chain Extension for TLS](https://tools.ietf.org/html/draft-ietf-tls-dnssec-chain-extension-07)_ has expired on 22/09/2018, more than one year ago.

**Comment by Darkspirit** [comment]
DNSSEC and DANE are increasingly adopted by government infrastructures and are also required by EU GDPR in the long term (state of the art protections): https://mecsa.jrc.ec.europa.eu/en/faq
DANE adoption stats:
https://stats.dnssec-tools.org/#graphs
https://mail.sys4.de/pipermail/dane-users/2019-September/000532.html

MTA-STS is an inferior and unnecessarily complex mechanism used by a minority who delays securing their DNS.
Like Cloudflare, PowerDNS, Google Domains, etc., they should use efficent ECDSA-based DNSSEC and ideally return [smaller NSEC](https://blog.cloudflare.com/black-lies/) responses, but instead they don't care, or quote problems of worst practices (RSA usage, huge responses, hostile software, etc.).

**Comment by HLFH** [comment]
Thank you for the details about EU law and the JRC.

Article 25 & 32 mention _taking into account the state of the art_.
The online tool MECSA developed by the Joint Research Centre [also provides a test for the new security standard MTA-STS](https://mecsa.jrc.ec.europa.eu/en/news).

Neither inferior nor complex is MTA-STS. It is only your opinion.
I've fully deployed DNSSEC on my side, and I currently prefer MTA-STS to DANE for SMTP.

**I am closing the issue as the MECSA tool as well as Hardenize recommend both support for MTA-STS & DANE for SMTP.**

I recommend to monitor the deployment of MTA-STS versus DANE for SMTP. It will be interesting in the next few years.

**Comment by ivanr** [comment]
@HLFH For better or worse, our current policy is to avoid taking sides. Specifically regarding DNSSEC and DANE and MTA-STS, it seems that the world is very divided. We don't think that anyone we could say would help with that, and we don't think it's our place to decide. Thus, we make recommendations that are in line with globally-accepted best practices.
