### ISSUE TITLE
#summary is `wrong`

### ISSUE THREAD

**Issue by andreasschulze** [hardenize/hardenize-public#69]
have a look at https://www.hardenize.com/report/postfix-buster.dev.somaf.de/1575724850#summary

I checked a v6-only MTA. The summay text isn't really true :-)

**Comment by ivanr** [comment]
Hello @andreasschulze I looked at the summary but didn't quite get what's wrong with it. Could you please clarify? Thanks.

**Comment by andreasschulze** [comment]
Oh, the text is now different. It said "
```
No SMTP servers

This host doesn't specify any SMTP servers, which probably means that it doesn't receive email. We are unable to evaluate STARTTLS support, TLS, X.509, and DANE configuration.
```
But now, as I added an MX-Record that text is no longer visible. In fact, I scanned a DNS-Label with AAAA Record pointing to a host with port 25 only open and no MX Record.

**Comment by ivanr** [comment]
That's strange. Normally, if there are no MX records we check the A/AAAA records instead. That should have picked up the SMTP service when you're testing the host that has it. I took a brief look at the code and should internally emulate the configuration you have now.

If you don't mind removing the MX record, I'd be happy to fix any problems that show up. Thanks!

**Comment by andreasschulze** [comment]
removed the MX record again
now https://www.hardenize.com/report/postfix-buster.dev.somaf.de/1575994852#summary
again say "
```
No SMTP servers

This host doesn't specify any SMTP servers, which probably means that it doesn't receive email. We are unable to evaluate STARTTLS support, TLS, X.509, and DANE configuration.
```
which is clearly different then "#email"

**Comment by ivanr** [comment]
I made a small fix, take a look at our staging server: https://staging.hardenize.net/report/postfix-buster.dev.somaf.de/1576084506 I think the result is now as expected. Thanks for your report!
