### ISSUE TITLE
AXFR test only checking the apex domain and not NS of tested domain?

### ISSUE THREAD

**Issue by Darkspirit** [hardenize/hardenize-public#8]
It is possible that you currently only check the apex domain and don't look if the tested domain has an own NS record? Your DNS table doesn't show the "dev.terrax.net NS" record:

https://www.hardenize.com/report/dev.terrax.net/1508031940#domain_dns
> Zone transfer is not allowed from public IP addresses.

no results: `dig AXFR terrax.net @gw1.h.terrax.net`
has results: `dig AXFR dev.terrax.net @dev.h.terrax.net`

----

http://dnsviz.net/d/dev.terrax.net/dnssec/ (uses Ed25519 btw)

> dev.terrax.net/SOA: The server returned a no error (NOERROR) response when queried for dev.terrax.net having record data of type SOA, but returned a name error (NXDOMAIN) when queried for dev.terrax.net having record data of type A.

This is because https://github.com/bluejekyll/trust-dns is under development. Hopefully mainstream/stable dns servers don't have such a problem.

**Comment by ivanr** [comment]
Fixed: https://www.hardenize.com/report/dev.terrax.net/1508150919#domain_dns
You were right, I was checking only against the apex host. I've changed that now to try the assessment host first; if unsuccessful, I'll then try the apex host. Thanks!
